org.gradle.jvmargs=-Xmx2G

# Mod properties
mod_id=justenoughfilters
mod_version=3.2.0
maven_group=net.psunset

# Required Common Dependencies
minecraft_version=26.2
minecraft_display_version=26.2
minecraft_version_fabric_range=>=26.2
minecraft_version_neoforge_range=[26.2,)
parchment_mappings_version=MISSING

# Optional Common Dependencies
jei_version=30.16.0.125
rei_version=26.2.820
emi_version=MISSING

# Required Fabric Dependencies
fabric_loader_version=0.19.3
fabric_loader_version_range=*
fabric_api_version=0.156.0
fabric_api_version_range=*
fabric_kotlin_version=1.13.12+kotlin.2.4.0
fabric_kotlin_version_range=*

# Optional Fabric Dependencies
modmenu_version=20.0.1

# Required NeoForge Dependencies
neoforge_version=26.2.0.43-beta
neoforge_version_range=[26,)
kff_version=6.3.0
kff_version_range=[6,)

# Optional NeoForge

# Non-mod Libraries