org.gradle.jvmargs=-Xmx2G

# Mod properties
mod_id=justenoughfilters
mod_version=2.4.0
maven_group=net.psunset

# Required Common Dependencies
minecraft_version=1.21.11
minecraft_version_file_range=1.21.11
minecraft_version_fabric_range=>=1.21.11 <26
minecraft_version_neoforge_range=[1.21.11,26)
parchment_mappings_version=2025.12.20
cloth_config_version=21.11.153
cloth_config_version_fabric_range=>=21.11 <26
cloth_config_version_neoforge_range=[21.11,26)

# Optional Common Dependencies
jei_version=27.4.0.22
rei_version=21.11.814
emi_version=MISSING

# Required Fabric Dependencies
fabric_loader_version=0.19.3
fabric_loader_version_range=*
fabric_api_version=0.141.4
fabric_api_version_range=*
fabric_kotlin_version=1.13.9+kotlin.2.3.10
fabric_kotlin_version_range=*
modmenu_version=17.0.0
modmenu_version_range=*

# Optional Fabric Dependencies

# Required NeoForge Dependencies
neoforge_version=21.11.42
neoforge_version_range=[21.11,26)
kff_version=6.2.0
kff_version_range=[6,)

# Optional NeoForge

# Non-mod Libraries