architectury {
    common('fabric', 'neoforge')
}

loom {
    accessWidenerPath = project(":fabric").file("src/main/resources/justenoughfilters.accesswidener")
}

dependencies {
    // For using @Environment and EnvType
    compileOnly "net.fabricmc:fabric-loader:$fabric_loader_version"

    compileOnly "mezz.jei:jei-$minecraft_version-common:$jei_version"
    compileOnly "mezz.jei:jei-$minecraft_version-gui:$jei_version"

    compileOnly "me.shedaniel:RoughlyEnoughItems-neoforge:$rei_version"

    // NOT support beyond 1.21.2
//    compileOnly "dev.emi:emi-xplat-intermediary:$emi_version+$minecraft_version"
}
